INSERT INTO tag_detail VALUES(1,1,1,NULL,' ',1,'atores.atores');
INSERT INTO tag_detail VALUES(2,1,2,'É associação','false',NULL,'atores.eh_associacao');
INSERT INTO tag_detail VALUES(3,2,1,NULL,' ',1,'cidade.cidade');
INSERT INTO tag_detail VALUES(4,3,2,'Não houve conflito','false',NULL,'conflito.nao_houve_conflito');
INSERT INTO tag_detail VALUES(5,3,2,'Entre Manifestantes','false',NULL,'conflito.entre_manifestantes');
INSERT INTO tag_detail VALUES(6,3,2,'Manifestantes x Polícia','false',NULL,'conflito.manifestantes_policia');
INSERT INTO tag_detail VALUES(7,3,2,'Manifestantes x Jornalistas','false',NULL,'conflito.manifestantes_jornalistas');
INSERT INTO tag_detail VALUES(8,3,2,'Manifestantes x Cidadãos','false',NULL,'conflito.manifestantes_cidadaos');
INSERT INTO tag_detail VALUES(9,3,2,'Polícia x Jornalistas','false',NULL,'conflito.policia_jornalistas');
INSERT INTO tag_detail VALUES(10,3,2,'Polícia x Cidadãos','false',NULL,'conflito.policia_cidadaos');
INSERT INTO tag_detail VALUES(11,4,1,NULL,'',4,'data.data');
INSERT INTO tag_detail VALUES(12,10,4,'Dias',' ',2,'duracao.dias');
INSERT INTO tag_detail VALUES(13,5,2,'Uso de redes sociais','false',' ','formas_de_convocacao.uso_de_redes_sociais');
INSERT INTO tag_detail VALUES(14,6,1,NULL,' ',1,'local.local');
INSERT INTO tag_detail VALUES(15,7,1,NULL,' ',2,'numero_de_feridos.numero_de_feridos');
INSERT INTO tag_detail VALUES(16,7,2,'Houve mortos?','false',NULL,'numero_de_feridos.houve_mortos');
INSERT INTO tag_detail VALUES(17,8,4,'Polícia',' ',2,'numero_de_manifestantes.policia');
INSERT INTO tag_detail VALUES(18,8,4,'Imprensa',' ',2,'numero_de_manifestantes.manifestantes');
INSERT INTO tag_detail VALUES(19,8,4,'Manifestantes',' ',2,'numero_de_manifestantes.manifestantes');
INSERT INTO tag_detail VALUES(20,9,1,NULL,' ',2,'numero_de_presos.numero_de_presos');
INSERT INTO tag_detail VALUES(22,14,1,NULL,' ',1,'slogans.slogans');
INSERT INTO tag_detail VALUES(23,13,1,NULL,' ',1,'simbolos_audiovisuais');
INSERT INTO tag_detail VALUES(24,11,1,NULL,' ',1,'temas.temas');
INSERT INTO tag_detail VALUES(25,11,3,'A favor','false',NULL,'temas.a_favor');
INSERT INTO tag_detail VALUES(26,11,3,'Contra','false',NULL,'temas.en_contra');
INSERT INTO tag_detail VALUES(27,15,4,'Verbo',NULL,1,'tipos_de_acao.instrumento');
INSERT INTO tag_detail VALUES(28,15,4,'Objeto',NULL,1,'tipos_de_acao.objeto');
INSERT INTO tag_detail VALUES(29,15,4,'Instrumento',NULL,1,'tipos_de_acao.verbo');
INSERT INTO tag_detail VALUES(30,5,1,NULL,NULL,1,'formas_de_convocacao.formas_de_convocacao');
INSERT INTO tag_detail VALUES(31,12,4,'Tipo de forca de seguranca',NULL,1,'repertorio_policial.tipo_de_forca_de_seguranca');
INSERT INTO tag_detail VALUES(32,12,4,'Numero de agentes das forcas de seguranca',NULL,1,'repertorio_policial.numero_de_agentes_das_forcas_de_seguranca');
INSERT INTO tag_detail VALUES(33,12,4,'Equipamentos',NULL,1,'repertorio_policial.equipamentos');
INSERT INTO tag_detail VALUES(34,12,4,'Acao das forcas de seguranca',NULL,1,'repertorio_policial.acao_de_forcas_de_seguranca');
INSERT INTO tag_detail VALUES(1,1,1,NULL,' ',1,'atores.atores');
INSERT INTO tag_detail VALUES(2,1,2,'É associação','false',NULL,'atores.eh_associacao');
INSERT INTO tag_detail VALUES(3,2,1,NULL,' ',1,'cidade.cidade');
INSERT INTO tag_detail VALUES(4,3,2,'Não houve conflito','false',NULL,'conflito.nao_houve_conflito');
INSERT INTO tag_detail VALUES(5,3,2,'Entre Manifestantes','false',NULL,'conflito.entre_manifestantes');
INSERT INTO tag_detail VALUES(6,3,2,'Manifestantes x Polícia','false',NULL,'conflito.manifestantes_policia');
INSERT INTO tag_detail VALUES(7,3,2,'Manifestantes x Jornalistas','false',NULL,'conflito.manifestantes_jornalistas');
INSERT INTO tag_detail VALUES(8,3,2,'Manifestantes x Cidadãos','false',NULL,'conflito.manifestantes_cidadaos');
INSERT INTO tag_detail VALUES(9,3,2,'Polícia x Jornalistas','false',NULL,'conflito.policia_jornalistas');
INSERT INTO tag_detail VALUES(10,3,2,'Polícia x Cidadãos','false',NULL,'conflito.policia_cidadaos');
INSERT INTO tag_detail VALUES(11,4,1,NULL,'',4,'data.data');
INSERT INTO tag_detail VALUES(12,10,4,'Dias',' ',2,'duracao.dias');
INSERT INTO tag_detail VALUES(13,5,2,'Uso de redes sociais','false',' ','formas_de_convocacao.uso_de_redes_sociais');
INSERT INTO tag_detail VALUES(14,6,1,NULL,' ',1,'local.local');
INSERT INTO tag_detail VALUES(15,7,1,NULL,' ',2,'numero_de_feridos.numero_de_feridos');
INSERT INTO tag_detail VALUES(16,7,2,'Houve mortos?','false',NULL,'numero_de_feridos.houve_mortos');
INSERT INTO tag_detail VALUES(17,8,4,'Polícia',' ',2,'numero_de_manifestantes.policia');
INSERT INTO tag_detail VALUES(18,8,4,'Imprensa',' ',2,'numero_de_manifestantes.manifestantes');
INSERT INTO tag_detail VALUES(19,8,4,'Manifestantes',' ',2,'numero_de_manifestantes.manifestantes');
INSERT INTO tag_detail VALUES(20,9,1,NULL,' ',2,'numero_de_presos.numero_de_presos');
INSERT INTO tag_detail VALUES(22,14,1,NULL,' ',1,'slogans.slogans');
INSERT INTO tag_detail VALUES(23,13,1,NULL,' ',1,'simbolos_audiovisuais');
INSERT INTO tag_detail VALUES(24,11,1,NULL,' ',1,'temas.temas');
INSERT INTO tag_detail VALUES(25,11,3,'A favor','false',NULL,'temas.a_favor');
INSERT INTO tag_detail VALUES(26,11,3,'Contra','false',NULL,'temas.en_contra');
INSERT INTO tag_detail VALUES(27,15,4,'Verbo',NULL,1,'tipos_de_acao.instrumento');
INSERT INTO tag_detail VALUES(28,15,4,'Objeto',NULL,1,'tipos_de_acao.objeto');
INSERT INTO tag_detail VALUES(29,15,4,'Instrumento',NULL,1,'tipos_de_acao.verbo');
INSERT INTO tag_detail VALUES(30,5,1,NULL,NULL,1,'formas_de_convocacao.formas_de_convocacao');
INSERT INTO tag_detail VALUES(31,12,4,'Tipo de forca de seguranca',NULL,1,'repertorio_policial.tipo_de_forca_de_seguranca');
INSERT INTO tag_detail VALUES(32,12,4,'Numero de agentes das forcas de seguranca',NULL,1,'repertorio_policial.numero_de_agentes_das_forcas_de_seguranca');
INSERT INTO tag_detail VALUES(33,12,4,'Equipamentos',NULL,1,'repertorio_policial.equipamentos');
INSERT INTO tag_detail VALUES(34,12,4,'Acao das forcas de seguranca',NULL,1,'repertorio_policial.acao_de_forcas_de_seguranca');
